AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tweet-watcher

Resources:
  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SettingsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: keyword
          AttributeType: S
        - AttributeName: slack_ch
          AttributeType: S
        - AttributeName: end_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: keyword-index
          KeySchema:
            - AttributeName: keyword
              KeyType: HASH
            - AttributeName: slack_ch
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotificationsTable
      AttributeDefinitions:
        - AttributeName: tweet_uid
          AttributeType: S
        - AttributeName: slack_ch
          AttributeType: S
      KeySchema:
        - AttributeName: tweet_uid
          KeyType: HASH
        - AttributeName: slack_ch
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  SettingsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: settings_api.lambda_handler
      Runtime: python3.11
      CodeUri: settings_api/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
      Events:
        GetSettings:
          Type: Api
          Properties:
            Path: /settings
            Method: get
        CreateSetting:
          Type: Api
          Properties:
            Path: /settings
            Method: post
        UpdateSetting:
          Type: Api
          Properties:
            Path: /settings
            Method: put
        DeleteSetting:
          Type: Api
          Properties:
            Path: /settings
            Method: delete
