AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tweet-watcher

Resources:
  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SettingsTable
      AttributeDefinitions:
        - AttributeName: keyword
          AttributeType: S
        - AttributeName: slack_ch
          AttributeType: S
        - AttributeName: end_at
          AttributeType: S
      KeySchema:
        - AttributeName: keyword
          KeyType: HASH
        - AttributeName: slack_ch
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotificationsTable
      AttributeDefinitions:
        - AttributeName: tweet_uid
          AttributeType: S
        - AttributeName: slack_ch
          AttributeType: S
      KeySchema:
        - AttributeName: tweet_uid
          KeyType: HASH
        - AttributeName: slack_ch
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
