name: CI

on:
  push:
    branches: ["main", "feature/**", "chore/**"]
  pull_request:
    branches: ["main", "feature/**", "chore/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest moto boto3
      - name: Run tests
        run: pytest
